"""add failed status into filestatus enum

Revision ID: a177c6f65212
Revises: cdfb8ad0e526
Create Date: 2026-05-02 09:29:16.556864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a177c6f65212'
down_revision: Union[str, Sequence[str], None] = 'cdfb8ad0e526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE filestatus ADD VALUE 'FAILED'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
