"""Create initial tables for the speech project

Revision ID: b99d471310f0
Revises: 
Create Date: 2025-11-13 09:52:06.166858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b99d471310f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('USER', 'ADMIN', name='role'), server_default='USER', nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', postgresql.ENUM('UPLOADING', 'UPLOADED', 'TRANSCRIBING', 'TRANSCRIBED', 'TRANSLATING', 'TRANSLATED', name='filestatus'), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('storage_bucket', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('file_size', sa.BIGINT(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_status'), 'files', ['status'], unique=False)
    op.create_index(op.f('ix_files_user_id'), 'files', ['user_id'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('start_timestamp', sa.Float(), nullable=False),
    sa.Column('end_timestamp', sa.Float(), nullable=False),
    sa.Column('transcription_text', sa.TEXT(), nullable=True),
    sa.Column('translation_text', sa.TEXT(), nullable=True),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_file_id'), 'segments', ['file_id'], unique=False)
    op.create_table('transcription_corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.Uuid(), nullable=False),
    sa.Column('corrected_text', sa.TEXT(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'REJECTED', 'APPROVED', name='correctionstatus'), server_default='PENDING', nullable=True),
    sa.Column('used_for_training', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcription_corrections_segment_id'), 'transcription_corrections', ['segment_id'], unique=False)
    op.create_index(op.f('ix_transcription_corrections_status'), 'transcription_corrections', ['status'], unique=False)
    op.create_table('translation_corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.Uuid(), nullable=False),
    sa.Column('corrected_text', sa.TEXT(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'REJECTED', 'APPROVED', name='correctionstatus'), server_default='PENDING', nullable=True),
    sa.Column('used_for_training', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_corrections_segment_id'), 'translation_corrections', ['segment_id'], unique=False)
    op.create_index(op.f('ix_translation_corrections_status'), 'translation_corrections', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_corrections_status'), table_name='translation_corrections')
    op.drop_index(op.f('ix_translation_corrections_segment_id'), table_name='translation_corrections')
    op.drop_table('translation_corrections')
    op.drop_index(op.f('ix_transcription_corrections_status'), table_name='transcription_corrections')
    op.drop_index(op.f('ix_transcription_corrections_segment_id'), table_name='transcription_corrections')
    op.drop_table('transcription_corrections')
    op.drop_index(op.f('ix_segments_file_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_files_user_id'), table_name='files')
    op.drop_index(op.f('ix_files_status'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
