"""add people table and speaker relation

Revision ID: dfca5804b4a5
Revises: e9b19c2cf231
Create Date: 2026-02-03 12:31:52.006982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dfca5804b4a5'
down_revision: Union[str, Sequence[str], None] = 'e9b19c2cf231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_email'), 'people', ['email'], unique=True)
    op.create_index(op.f('ix_people_name'), 'people', ['name'], unique=False)
    op.add_column('files', sa.Column('speaker_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_files_speaker_id'), 'files', ['speaker_id'], unique=False)
    op.create_foreign_key(None, 'files', 'people', ['speaker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_index(op.f('ix_files_speaker_id'), table_name='files')
    op.drop_column('files', 'speaker_id')
    op.drop_index(op.f('ix_people_name'), table_name='people')
    op.drop_index(op.f('ix_people_email'), table_name='people')
    op.drop_table('people')
    # ### end Alembic commands ###
