"""Add pipeline config and logs tables

Revision ID: e9b19c2cf231
Revises: b99d471310f0
Create Date: 2025-11-19 17:08:16.191559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e9b19c2cf231'
down_revision: Union[str, Sequence[str], None] = 'b99d471310f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_type', postgresql.ENUM('ASR', 'MT', name='pipelinetasktype'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cron_schedule', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('min_samples_required', sa.Integer(), nullable=False),
    sa.Column('learning_rate', sa.Float(), nullable=False),
    sa.Column('num_epochs', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('evaluation_dataset_storage_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_configs_task_type'), 'pipeline_configs', ['task_type'], unique=True)
    op.create_table('pipeline_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cron_expression', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_run_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_run_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_id', sa.Uuid(), nullable=False),
    sa.Column('mlflow_run_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('status', postgresql.ENUM('RUNNING', 'SUCCESS', 'FAILED', 'SKIPPED', name='pipelinerunstatus'), nullable=True),
    sa.Column('data_samples_used', sa.Integer(), nullable=False),
    sa.Column('metrics_baseline', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics_new_model', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['pipeline_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_run_logs')
    op.drop_table('pipeline_schedules')
    op.drop_index(op.f('ix_pipeline_configs_task_type'), table_name='pipeline_configs')
    op.drop_table('pipeline_configs')
    # ### end Alembic commands ###
