"""add original text into corrections tables

Revision ID: f9d4387e4161
Revises: dfca5804b4a5
Create Date: 2026-02-10 20:12:24.748291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9d4387e4161'
down_revision: Union[str, Sequence[str], None] = 'dfca5804b4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription_corrections', sa.Column('original_text', sa.TEXT(), nullable=True))
    op.add_column('translation_corrections', sa.Column('original_text', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation_corrections', 'original_text')
    op.drop_column('transcription_corrections', 'original_text')
    # ### end Alembic commands ###
